version: "3"

services:
  #---------------------------------------
  # mongodb container
  #---------------------------------------
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    image: "mongo:${TAG_MONGO}"
    networks:
      - net
    ports:
      - ${PORT_MONGODB}:27017
    restart: "unless-stopped"
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb

  #---------------------------------------
  # mongodb container
  #---------------------------------------
  mongo-express:
    container_name: ${COMPOSE_PROJECT_NAME}_mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:27017/
    image: "mongo-express:${TAG_MONGO_EXPRESS}"
    networks:
      - net
    ports:
      - ${PORT_MONGO_EXPRESS}:8081
    restart: "unless-stopped"

networks:
  net:


volumes:
  mongodb_data:
