version: "3"

services:
  #---------------------------------------
  # mysql database container
  #---------------------------------------
  mysqldb:
    command: ${MYSQLDB_COMMAND}
    container_name: ${COMPOSE_PROJECT_NAME}_mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    image: "mysql:${TAG_MYSQL}"
    networks:
      - net
    ports:
      - ${PORT_MYSQL}:3306
    restart: "unless-stopped"
    volumes:
      # To initialise the db using sql scripts, create ./init_mysql
      # Place your sql scripts in ./init_mysql
      # Uncomment the following line
      # - ./init_mysql:/docker-entrypoint-initdb.d
      - mysqldb_data:/var/lib/mysql

  #---------------------------------------
  # phpmyadmin container
  #---------------------------------------
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: ${MYSQLDB_HOST}
      PMA_USER: ${MYSQLDB_ROOT_USER}
      PMA_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    image: "phpmyadmin:${TAG_PHPMYADMIN}"
    networks:
      - net
    ports:
      - "${PORT_PHPADMIN}:80"
    restart: "unless-stopped"

networks:
  net:


volumes:
  mysqldb_data:
